CREATE TABLE AIRLINE_DETAILS(
 PNR INT PRIMARY KEY,
 NAME VARCHAR(250) NOT NULL,
 SOURCE VARCHAR(250) NOT NULL,
 DESTINATION VARCHAR(250) NOT NULL,
 PRICE INT NOT NULL,
 HOPS INT DEFAULT NULL,
 TIME VARCHAR(250) NOT NULL,
 STATUS VARCHAR(30) NOT NULL);
 
 INSERT INTO AIRLINE_DETAILS(PNR, NAME, SOURCE , DESTINATION, PRICE , HOPS, TIME, STATUS) VALUES 
 ('1000','INDIGO','VISAKHAPATNAM','CHENNAI',2500,1,'12.15PM','DELAYED'),
 ('1001','SPICEJET','CHENNAI','VISAKHAPATNAM',3000,0,'4.00PM','DEPARTURED');
 